In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv("KaggleV2-May-2016.csv")
pd.set_option("display.max_columns", None)
df

PatientId  AppointmentID Gender          ScheduledDay  \
0       2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1       5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2       4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3       8.679512e+11        5642828      F  2016-04-29T17:29:31Z   
4       8.841186e+12        5642494      F  2016-04-29T16:07:23Z   
...              ...            ...    ...                   ...   
110522  2.572134e+12        5651768      F  2016-05-03T09:15:35Z   
110523  3.596266e+12        5650093      F  2016-05-03T07:27:33Z   
110524  1.557663e+13        5630692      F  2016-04-27T16:03:52Z   
110525  9.213493e+13        5630323      F  2016-04-27T15:09:23Z   
110526  3.775115e+14        5629448      F  2016-04-27T13:30:56Z   

              AppointmentDay  Age      Neighbourhood  Scholarship  \
0       2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0   
1       2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0   
2       2016-04-29T00:00:00Z   62      MATA DA PRAIA            0   
3       2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0   
4       2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0   
...                      ...  ...                ...          ...   
110522  2016-06-07T00:00:00Z   56        MARIA ORTIZ            0   
110523  2016-06-07T00:00:00Z   51        MARIA ORTIZ            0   
110524  2016-06-07T00:00:00Z   21        MARIA ORTIZ            0   
110525  2016-06-07T00:00:00Z   38        MARIA ORTIZ            0   
110526  2016-06-07T00:00:00Z   54        MARIA ORTIZ            0   

        Hipertension  Diabetes  Alcoholism  Handcap  SMS_received No-show  
0                  1         0           0        0             0      No  
1                  0         0           0        0             0      No  
2                  0         0           0        0             0      No  
3                  0         0           0        0             0      No  
4                  1         1           0        0             0      No  
...              ...       ...         ...      ...           ...     ...  
110522             0         0           0        0             1      No  
110523             0         0           0        0             1      No  
110524             0         0           0        0             1      No  
110525             0         0           0        0             1      No  
110526             0         0           0        0             1      No  

[110527 rows x 14 columns]

In [11]:
df.isnull()


PatientId  AppointmentID  Gender  ScheduledDay  AppointmentDay    Age  \
0           False          False   False         False           False  False   
1           False          False   False         False           False  False   
2           False          False   False         False           False  False   
3           False          False   False         False           False  False   
4           False          False   False         False           False  False   
...           ...            ...     ...           ...             ...    ...   
110522      False          False   False         False           False  False   
110523      False          False   False         False           False  False   
110524      False          False   False         False           False  False   
110525      False          False   False         False           False  False   
110526      False          False   False         False           False  False   

        Neighbourhood  Scholarship  Hipertension  Diabetes  Alcoholism  \
0               False        False         False     False       False   
1               False        False         False     False       False   
2               False        False         False     False       False   
3               False        False         False     False       False   
4               False        False         False     False       False   
...               ...          ...           ...       ...         ...   
110522          False        False         False     False       False   
110523          False        False         False     False       False   
110524          False        False         False     False       False   
110525          False        False         False     False       False   
110526          False        False         False     False       False   

        Handcap  SMS_received  No-show  
0         False         False    False  
1         False         False    False  
2         False         False    False  
3         False         False    False  
4         False         False    False  
...         ...           ...      ...  
110522    False         False    False  
110523    False         False    False  
110524    False         False    False  
110525    False         False    False  
110526    False         False    False  

[110527 rows x 14 columns]

In [12]:
df.isnull().sum()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [13]:
med_df = df[['Gender', 'Age', 'Scholarship', 'Hipertension', 'Diabetes', 'Alcoholism', 'SMS_received','Handcap', 'No-show']]
med_df

Gender  Age  Scholarship  Hipertension  Diabetes  Alcoholism  \
0           F   62            0             1         0           0   
1           M   56            0             0         0           0   
2           F   62            0             0         0           0   
3           F    8            0             0         0           0   
4           F   56            0             1         1           0   
...       ...  ...          ...           ...       ...         ...   
110522      F   56            0             0         0           0   
110523      F   51            0             0         0           0   
110524      F   21            0             0         0           0   
110525      F   38            0             0         0           0   
110526      F   54            0             0         0           0   

        SMS_received  Handcap No-show  
0                  0        0      No  
1                  0        0      No  
2                  0        0      No  
3                  0        0      No  
4                  0        0      No  
...              ...      ...     ...  
110522             1        0      No  
110523             1        0      No  
110524             1        0      No  
110525             1        0      No  
110526             1        0      No  

[110527 rows x 9 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

med_df['Gender'] = encoder.fit_transform(df['Gender'])
med_df['No-show'] = encoder.fit_transform(df['No-show'])
med_df

C:\Users\sachi\AppData\Local\Temp\ipykernel_31588\925051157.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  med_df['Gender'] = encoder.fit_transform(df['Gender'])
C:\Users\sachi\AppData\Local\Temp\ipykernel_31588\925051157.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  med_df['No-show'] = encoder.fit_transform(df['No-show'])


Gender  Age  Scholarship  Hipertension  Diabetes  Alcoholism  \
0            0   62            0             1         0           0   
1            1   56            0             0         0           0   
2            0   62            0             0         0           0   
3            0    8            0             0         0           0   
4            0   56            0             1         1           0   
...        ...  ...          ...           ...       ...         ...   
110522       0   56            0             0         0           0   
110523       0   51            0             0         0           0   
110524       0   21            0             0         0           0   
110525       0   38            0             0         0           0   
110526       0   54            0             0         0           0   

        SMS_received  Handcap  No-show  
0                  0        0        0  
1                  0        0        0  
2                  0        0        0  
3                  0        0        0  
4                  0        0        0  
...              ...      ...      ...  
110522             1        0        0  
110523             1        0        0  
110524             1        0        0  
110525             1        0        0  
110526             1        0        0  

[110527 rows x 9 columns]

In [15]:
x_columns = 8
X = med_df.iloc[:, 0: x_columns].values
y = med_df.iloc[:, x_columns].values
y

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
med_df = scale.fit_transform(med_df)
med_df


array([[-0.73383659,  1.07793239, -0.33011206, ..., -0.68761155,
        -0.13772244, -0.50301783],
       [ 1.36270119,  0.81830565, -0.33011206, ..., -0.68761155,
        -0.13772244, -0.50301783],
       [-0.73383659,  1.07793239, -0.33011206, ..., -0.68761155,
        -0.13772244, -0.50301783],
       ...,
       [-0.73383659, -0.69618366, -0.33011206, ...,  1.45430948,
        -0.13772244, -0.50301783],
       [-0.73383659,  0.03942544, -0.33011206, ...,  1.45430948,
        -0.13772244, -0.50301783],
       [-0.73383659,  0.73176341, -0.33011206, ...,  1.45430948,
        -0.13772244, -0.50301783]])

In [17]:
from sklearn.model_selection import train_test_split
train_ratio = 0.80
test_ratio = 0.10
validation_ratio = 0.10

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_ratio)
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size = validation_ratio)


print(X_train.shape)
print(X_test.shape)
print(X_valid.shape)

(99474, 8)
(11053, 8)
(11053, 8)


In [18]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = "gini", splitter='best', max_leaf_nodes = 50000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
score = model.score(X_test, y_test)
print(score)

0.8002352302542296


In [19]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[8789   23]
 [2185   56]]


In [20]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      8812
           1       0.71      0.02      0.05      2241

    accuracy                           0.80     11053
   macro avg       0.75      0.51      0.47     11053
weighted avg       0.78      0.80      0.72     11053



In [21]:
from sklearn.ensemble import RandomForestClassifier
model_RF = RandomForestClassifier(n_estimators = 1000, bootstrap = True)
model_RF.fit(X_train, y_train)

y_pred_RF = model_RF.predict(X_test)
score_RF = model.score(X_test, y_test)
print(score_RF)

0.8002352302542296


In [22]:
#Both classifications provide similar results of 80% accuracy.